routes/web.php
        'as' => 'inventories.activos.insumos.edit',
        'uses' => 'InventoriesActivesController@edit',
    ]);

    Route::post('inventories/activos-insumos/{id}', [
        'as' => 'inventories.activos.insumos.update',
        'uses' => 'InventoriesActivesController@update',
    ]);

    Route::get('inventories/activos-insumos/{kardex_type}/{folio}/{type}', [
        'as' => 'inventories.insumos.ticket',
        'uses' => 'InventoriesActivesController@show',
    ]);

    Route::resource('articles', 'ArticlesController');

    Route::get('inventories/warehouse/adjustments', [
        'as' => 'home.inventories.warehouse.adjustments.index',
        'uses' => 'InventoriesController@indexWarehouseAdjustments',
    ]);
    Route::get('inventories/warehouse/adjustments/create', [
        'as' => 'home.inventories.warehouse.adjustments.create',
        'uses' => 'InventoriesController@createWarehouseAdjustment',
    ]);
    Route::get('inventories/warehouse/adjustments/{folio}/print', [
        'as' => 'home.inventories.warehouse.adjustments.print',
        'uses' => 'InventoriesController@printWarehouseAdjustment',
    ]);
    Route::post('inventories/warehouse/adjustments/store', [
        'as' => 'home.inventories.warehouse.adjustments.store',
        'uses' => 'InventoriesController@storeWarehouseAdjustment',
    ]);

    Route::get('inventories/{type}/{folio}/{subsidiary_id}', [
        'as' => 'inventories.ticket',
        'uses' => 'InventoriesController@show',
    ]);

    Route::get('api/products/{key}', 'ProductsController@getByKey');
    Route::get('api/warehouse/products/{code}', 'WarehouseProductsController@getByCode');
    Route::get('api/articles/{key}', 'ArticlesController@getByKey');
    Route::resource('products', 'ProductsController');
    Route::resource('services', 'ServicesController');
    Route::post('services/updateSubsidiaryPrices', [
        'as' => 'services.update_subsidiary_prices',
        'uses' => 'ServicesController@updateSubsidiaryPrices',
    ]);
    Route::post('products/updateSubsidiaryPrices', [
        'as' => 'products.update_subsidiary_prices',
        'uses' => 'ProductsController@updateSubsidiaryPrices',
    ]);

    Route::resource('subsidiaries', 'SubsidiariesController');
    Route::resource('subsidiaries.turns', 'SubsidiariesTurnsController');
    Route::post('subsidiaries/{id}/users', [
        'as' => 'subsidiaries.users',
        'uses' => 'SubsidiariesController@asignUsers',
    ]);
    Route::post('subsidiaries/{id}/employees', [
        'as' => 'subsidiaries.employees',
        'uses' => 'SubsidiariesController@asignEmployees',
    ]);

    Route::post('employees/signin', [
        'as' => 'employees.verify.sign',
        'uses' => 'EmployeesController@show',
    ]);
    Route::put('employees/{id}/doctos', [
        'as' => 'employees.upload.documents',
        'uses' => 'EmployeesController@addDocuments',
    ]);
    Route::get('employees/{id}/contrato', [
        'as' => 'employees.contrato',
        'uses' => 'EmployeesController@contrato',
    ]);
    Route::put('employees/{id}/active', [
        'as' => 'employees.active',
        'uses' => 'EmployeesController@active',
    ]);

    Route::put('products/{id}/active', [
        'as' => 'products.active',
        'uses' => 'ProductsController@active',
    ]);

    Route::resource('alerts', 'AlertsController', ['except' => ['show']]);
    Route::get('alerts/today', [
        'as' => 'alerts.todayAlerts',
        'uses' => 'AlertsController@todayAlerts',
    ]);
    Route::put('alerts/{id}/active', [
        'as' => 'alerts.active',
        'uses' => 'AlertsController@active',
    ]);

    Route::resource('employees', 'EmployeesController', ['except' => ['show']]);

    Route::get('employees/{employee_request_id}/from-request', [
        'as' => 'employees.from-request',
        'uses' => 'EmployeesController@createFromRequest',
    ]);

    Route::get('employees/{id}/schedules/print', [
        'as' => 'employees.schedules.print',
        'uses' => 'EmployeesSchedulesController@print',
    ]);

    Route::resource('employees.schedules', 'EmployeesSchedulesController');
    Route::resource('employees.exchanges', 'ScheduleExchangesController');

    Route::post('exchanges/{id}/authorizee', [
        'as' => 'employees.exchanges.authorizee',
        'uses' => 'ScheduleExchangesController@authorizee',
    ]);
    Route::post('exchanges/{id}/unauthorize', [
        'as' => 'employees.exchanges.unauthorize',
        'uses' => 'ScheduleExchangesController@unauthorize',
    ]);
    Route::post('exchanges/{id}/authorizeadmin', [
        'as' => 'employees.exchanges.authorizeadmin',
        'uses' => 'ScheduleExchangesController@authorizeadmin',
    ]);
    Route::post('exchanges/{id}/unauthorizeadmin', [
        'as' => 'employees.exchanges.unauthorizeadmin',
        'uses' => 'ScheduleExchangesController@unauthorizeadmin',
    ]);

    Route::post('exchanges.unauthorize','ScheduleExchangesController@unauthorize');

    Route::post('employees/signin', [
        'as' => 'employees.verify.sign',
        'uses' => 'EmployeesController@show',
    ]);

    Route::resource('employees.disabilities', 'EmployeesDisabilitiesController');
    Route::resource('employees.issues', 'EmployeesIssuesController');

    Route::delete('/images/{id}', [
        'as' => 'destroy.images',
        'uses' => 'ImagesController@destroy',
    ]);

    Route::put('/schedules/{id}/unlock', [
        'as' => 'employees.schedules.unlock',
        'uses' => 'EmployeesSchedulesController@unLock',
    ]);

    Route::resource('users', 'UsersController');
    Route::resource('configurations', 'ConfigurationController');

    Route::get('configuration/{id}/edit', [
        'as' => 'admin.configurations.edit',
        'uses' => 'ConfigurationController@edit',
    ]);

    Route::get('configuration/create', [
        'as' => 'admin.configurations.create',
        'uses' => 'ConfigurationController@Create',
    ]);

    Route::get('paysheets/{key}/archive', 'PaysheetsController@archive');
    Route::get('paysheets/{key}/export/original', 'PaysheetsController@original');
    Route::get('paysheets/{key}/export/nomina', 'PaysheetsController@nomina');
    Route::get('paysheets/{key}/export/banco', 'PaysheetsController@banco');
    Route::put('paysheets/{id}/refresh', [
        'as' => 'paysheets.refresh',
        'uses' => 'PaysheetsController@refresh'
    ]);
    Route::post('paysheets/updateById', 'PaysheetsController@updateById');
    Route::post('paysheets/archiveById', 'PaysheetsController@archiveById');
    Route::resource('paysheets', 'PaysheetsController');

    Route::get('configuration/addRate', [
        'as' => 'configuration.rate.create',
        'uses' => 'ConfigurationController@createRate'
    ]);
    Route::post('configurations/rates', 'ConfigurationController@storeRate');
    Route::get('configurations/createJob', 'ConfigurationController@createJob');
    Route::post('configurations/jobs', 'ConfigurationController@storeJob');
    Route::get('configurations/turns', 'ConfigurationController@createTurn');
    Route::post('configurations/turns', 'ConfigurationController@storeTurn');
    Route::get('configurations/turns/{id}', 'ConfigurationController@editTurn');
    Route::put('configurations/turns/{id}', 'ConfigurationController@updateTurn');

    Route::get('configurations/devices', 'ConfigurationController@createDevice');
    Route::post('configurations/devices', 'ConfigurationController@storeDevice');
    Route::get('configurations/devices/{id}', 'ConfigurationController@editDevice');
    Route::put('configurations/devices/{id}', 'ConfigurationController@updateDevice');
    Route::put('configuration/{id}/edit', [
        'as' => 'configurations.updateFiles',
        'uses' => 'ConfigurationController@updateFiles',
    ]);
    // Reportes
    Route::get('reports/attendances', 'ReportsController@attendances');
    Route::post('reports/attendance_time/{id}', [
        'as' => 'time.edit',
        'uses' => 'ReportsController@attendancesTime',
    ]);
    Route::delete('reports/attendances/{id}', ['as' => 'delete_attendance', 'uses' => 'ReportsController@destroyAttendances']);
    Route::get('reports/issues', 'ReportsController@issues');
    Route::get('reports/schedules', 'ReportsController@schedules');
    Route::get('reports/attendance-card', 'ReportsController@attendanceCard');
    Route::get('reports/cashCutsByDate', 'ReportsController@cashCutsByDate');
    Route::get('reports/cashierMovementsResume', 'ReportsController@cashierMovementsResume');

    Route::get('reports/subsidiary', 'ReportsController@subsidiary');
    Route::get('reports/subsidiaries', 'ReportsController@subsidiaries')->name('report.subsidiaries');
    Route::get('reports/barber', 'ReportsController@barber');
    Route::get('reports/subsidiaries/turns', 'ReportsController@turns');
    Route::get('reports/flow', 'ReportsController@flow');
    Route::get('reports/daily', 'ReportsController@daily');
    Route::get('reports/daily-laundry-services', 'ReportsController@dailyLaundryServices');
    Route::get('reports/accumulated-daily', 'ReportsController@accumulatedDaily');
    Route::get('reports/daily-turns', 'ReportsController@dailyTurns');
    Route::get('reports/daily-cuts', 'ReportsController@dailyCuts');
    Route::get('reports/weekly/barbers', 'ReportsController@weeklyBarber');
    Route::get('reports/weekly/sold-products', 'ReportsController@soldProducts');
    Route::get('reports/sold-products', [
        'as' => 'reports.sales.sold-products-employee',
        'uses' => 'ReportsController@soldProductsByEmployee',
    ]);
    Route::get('reports/weekly/subsidiary-analysis', 'ReportsController@subsidiaryAnalysis');
    Route::get('reports/weekly/services/barbers', 'ReportsController@weeklyServicesBarber');
    Route::get('reports/weekly/barbers/excellence', 'ReportsController@employeesExcellence');

app/Alert.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Alert extends Model
{
    protected $fillable = [
        'subsidiary_id', 'name', 'message', 'subsidiary_id', 'monday', 'tuesday', 
        'wednesday', 'thursday', 'friday', 'saturday', 'sunday', 'time', 'is_active'
    ];

    public function scopeActive($query)
    {
        return $query->where('is_active', true);
    }

    public function scopeNotActive($query)
    {
        return $query->where('is_active', false);
    }

    public function subsidiary()
    {
        return $this->belongsTo(Subsidiary::class);
    }
}

app/Http/Controllers/AlertsController.php
<?php

namespace App\Http\Controllers;

use App\Alert;
use App\Subsidiary;
use App\Traits\SubDomainHelper;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AlertsController extends Controller
{
    use SubDomainHelper;

    public function index()
    {
        $alerts = Alert::active()->get();
        $inactive_alerts = Alert::notActive()->get();
        return view('admin.alerts.index', compact('alerts','inactive_alerts'));
    }

    public function todayAlerts()
    {
        $alerts = Alert::active()
        ->where(strtolower(date('l')), true);

        if ($subsidiary = $this->getSubsidiary()) {
            $subsidiary_id = $subsidiary->id;
            $alerts = $alerts->where(function ($q) use ($subsidiary_id) {
                $q->where('subsidiary_id', null)
                ->orWhere('subsidiary_id', $subsidiary_id);
            });
        }

        $alerts = $alerts->get();

        return response()->json([
            'success' => true,
            'alerts' => $alerts
        ]);
    }


    public function create()
    {
        $subsidiaries = $this->getSubsidiaries();
        return view('admin.alerts.create', compact('subsidiaries'));
    }

    public function store(Request $request)
    {
        $data = $request->all();
        if(empty($request->subsidiary_id)) {
            $data['subsidiary_id'] = null;
        }
        $alert = Alert::create($data);
        $request->session()->flash('success', 'Alerta creada con éxito.');
        return redirect()->route('alerts.edit', $alert->id);
    }

    public function edit(Request $request, $id)
    {
        $alert = Alert::find($id);
        $subsidiaries = $this->getSubsidiaries();
        return view('admin.alerts.edit', compact('alert', 'subsidiaries'));
    }

    public function update(Request $request, $id)
    {
        $data = $request->all();
        if(empty($request->subsidiary_id)) $data['subsidiary_id'] = null;

        // validate days
        $data['monday'] = $request->monday ? $request->monday : 0; 
        $data['tuesday'] = $request->tuesday ? $request->tuesday : 0; 
        $data['wednesday'] = $request->wednesday ? $request->wednesday : 0; 
        $data['thursday'] = $request->thursday ? $request->thursday : 0; 
        $data['friday'] = $request->friday ? $request->friday : 0; 
        $data['saturday'] = $request->saturday ? $request->saturday : 0; 
        $data['sunday'] = $request->sunday ? $request->sunday : 0; 

        $data['time'] = date("H:i", strtotime($data['time']));

        $alert = Alert::find($id);
        $alert->update($data);

        $request->session()->flash('success', 'Alerta actualizada con éxito.');
        return redirect()->route('alerts.edit', $alert->id);
    }

    public function destroy(Request $request, $id)
    {
        $alert = Alert::find($id);
        $alert->update(['is_active' => false]);
        $request->session()->flash('success', 'Alerta dada de baja con éxito');
        return redirect()->route('alerts.index');
    }

    public function active(Request $request, $id)
    {
        $alert = Alert::find($id);
        $alert->update(['is_active' => true]);
        $request->session()->flash('success', 'Alerta dada de alta con éxito.');
        return back();
    }

    public function getSubsidiary()
    {
        if ($subsidiary_code = $this->hasSubdomain()) {
            return Subsidiary::whereKey($subsidiary_code)->firstOrFail();
        }
        return false;
    }

    private function getSubsidiaries(){
        $subsidiaries = Subsidiary::where('is_active', true);
        $user = Auth::user();
        if($user->access_subsidiary_id != null){
            $subsidiaries = $subsidiaries->where('id',$user->access_subsidiary_id);
        }
        return $subsidiaries->get();
    }
}

resources/views/admin/alerts/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Promociones
                    <p class="pull-right help-block">Campos con * son obligatorios.</p>
                </div>

                <div class="panel-body" style="padding: 0px 50px;">
                    <form action="{{route('alerts.store')}}" method="POST" class="form-horizontal">
                        {{{ csrf_field() }}}

                        <div class="form-group">
                            <div class="col-sm-6">
                                <label for="name" class="control-label">Nombre *</label>
                                <input type="text" class="form-control" id="name" name="name">
                            </div>

                            <div class="col-sm-6">
                                <label for="message" class="control-label">Mensaje *</label>
                                <input type="text" class="form-control" id="message" name="message">
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <div class="col-sm-6">
                                <label for="name" class="control-label" style="padding-bottom: 5px;">Días donde se mostrará *</label>
                                <br>
                                <label><input type="checkbox" name="monday" value="1" /> Lun</label>&nbsp;
                                <label><input type="checkbox" name="tuesday" value="1" /> Mar</label>&nbsp;
                                <label><input type="checkbox" name="wednesday" value="1" /> Mie</label>&nbsp;
                                <label><input type="checkbox" name="thursday" value="1" /> Jue</label>&nbsp;
                                <label><input type="checkbox" name="friday" value="1" /> Vie</label>&nbsp;
                                <label><input type="checkbox" name="saturday" value="1" /> Sab</label>&nbsp;
                                <label><input type="checkbox" name="sunday" value="1" /> Dom</label>
                            </div>
                            <div class="col-sm-6">
                                <label for="start">Hora del mensaje : </label>
                                <div class="bootstrap-timepicker timepicker">
                                    <input type="text" class="form-control timeinput" style="text-align: center;" name="time">
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-6">
                                <label for="email" class="control-label">Sucursal *</label>
                                <select class="form-control" name="subsidiary_id" id="subsidiary_id">
                                    <option value="0">Todas</option>
                                    @foreach($subsidiaries as $subsidiary)
                                        <option value="{{$subsidiary->id}}">{{ $subsidiary->name }}</option>
                                    @endforeach 
                                </select>
                            </div>
                        </div>

                        <hr>
                        <div class="form-group">
                            <div class="col-md-9">
                            </div>
                            <div class="col-md-3">
                                <input type="submit" class="btn btn-primary" value="Guardar">
                                <a href="{{route('promotions.index')}}" class="btn btn-default" >Cancelar</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/alerts/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Alertas
                    <p class="pull-right help-block">Campos con * son obligatorios.</p>
                </div>

                <div class="panel-body" style="padding: 0px 50px;">
                    <form action="{{route('alerts.update', $alert->id)}}" method="POST" class="form-horizontal">
                        {{{ csrf_field() }}}
                        {{{ method_field('PUT') }}}

                        <div class="form-group">
                            <div class="col-sm-6">
                                <label for="name" class="control-label">Nombre *</label>
                                <input type="text" class="form-control" id="name" name="name" value="{{ $alert->name }}">
                            </div>

                            <div class="col-sm-6">
                                <label for="message" class="control-label">Mensaje *</label>
                                <input type="text" class="form-control" id="message" name="message" value="{{ $alert->message }}">
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <div class="col-sm-6">
                                <label for="name" class="control-label" style="padding-bottom: 5px;">Días donde se mostrará *</label>
                                <br>
                                <label><input type="checkbox" name="monday" value="1" @if($alert->monday) checked @endif/> Lun</label>&nbsp;
                                <label><input type="checkbox" name="tuesday" value="1" @if($alert->tuesday) checked @endif/> Mar</label>&nbsp;
                                <label><input type="checkbox" name="wednesday" value="1" @if($alert->wednesday) checked @endif/> Mie</label>&nbsp;
                                <label><input type="checkbox" name="thursday" value="1" @if($alert->thursday) checked @endif/> Jue</label>&nbsp;
                                <label><input type="checkbox" name="friday" value="1" @if($alert->friday) checked @endif/> Vie</label>&nbsp;
                                <label><input type="checkbox" name="saturday" value="1" @if($alert->saturday) checked @endif/> Sab</label>&nbsp;
                                <label><input type="checkbox" name="sunday" value="1" @if($alert->sunday) checked @endif/> Dom</label>
                            </div>
                            <div class="col-sm-6">
                                <label for="start">Hora del mensaje : </label>
                                <div class="bootstrap-timepicker timepicker">
                                    <input type="text" class="form-control timeinput" style="text-align: center;" name="time" value="{{ $alert->time }}">
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-6">
                                <label for="email" class="control-label">Sucursal *</label>
                                <select class="form-control" name="subsidiary_id" id="subsidiary_id">
                                    <option value="0">Todas</option>
                                    @foreach($subsidiaries as $subsidiary)
                                        <option @if($alert->subsidiary_id == $subsidiary->id) selected="selected" @endif 
                                            value="{{$subsidiary->id}}">{{ $subsidiary->name }}</option>
                                    @endforeach 
                                </select>
                            </div>
                        </div>

                        <hr>
                        <div class="form-group">
                            <div class="col-md-9">
                            </div>
                            <div class="col-md-3">
                                <input type="submit" class="btn btn-primary" value="Guardar">
                                <a href="{{route('alerts.index')}}" class="btn btn-default" >Cancelar</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/alerts/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Alertas
                    <div class="pull-right">
                        <a href="{{route('alerts.create')}}">Agregar alerta</a>
                    </div>
                </div>

                <div class="panel-body">
                    <ul class="nav nav-tabs" role="tablist">
                        <li role="presentation" class="active"><a href="#actives" aria-controls="actives" role="tab" data-toggle="tab">Activas</a></li>
                        <li role="presentation"><a href="#inactives" aria-controls="inactives" role="tab" data-toggle="tab">Inactivas</a></li>
                    </ul>
                    <div class="tab-content">
                        <div role="tabpanel" class="tab-pane active" id="actives">
                            <table class="table table-striped datatables">
                                <thead>
                                    <tr>
                                        <th>Nombre</th>
                                        <th>Sucursal</th>
                                        <th>Horario</th>
                                        <th>Días</th>
                                        <th>Opciones</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($alerts as $alert)
                                        <tr>
                                            <td>{{ $alert->name }}</td>
                                            <td>
                                                @if($alert->subsidiary)
                                                    {{ $alert->subsidiary->name }}
                                                @else
                                                    TODAS
                                                @endif
                                            </td>
                                            <td>{{ $alert->time }}</td>
                                            <td>
                                                @if($alert->monday) lun, @endif
                                                @if($alert->tuesday) mar, @endif
                                                @if($alert->wednesday) mie, @endif
                                                @if($alert->thursday) jue, @endif
                                                @if($alert->friday) vie, @endif
                                                @if($alert->saturday) sab, @endif
                                                @if($alert->sunday) dom, @endif
                                            </td>
                                            <td>
                                                <a href="{{ route('alerts.edit', $alert->id) }}">Editar</a>
                                                @if(Auth::user()->isA('super-admin'))
                                                    |
                                                    <a href="#" data-toggle="modal" data-target="#modal-delete-{{$alert->id}}">
                                                        Dar de baja
                                                    </a>
                                                    @include('admin.alerts.partials.delete_modal', compact('alert'))
                                                @endif
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                        <div role="tabpanel" class="tab-pane" id="inactives">
                            <table class="table table-striped datatables">
                                <thead>
                                    <tr>
                                        <th>Nombre</th>
                                        <th>Sucursal</th>
                                        <th>Horario</th>
                                        <th>Días</th>
                                        <th>Opciones</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($inactive_alerts as $alert)
                                        <tr>
                                            <td>{{ $alert->name }}</td>
                                            <td>
                                                @if($alert->subsidiary)
                                                    {{ $alert->subsidiary->name }}
                                                @else
                                                    TODAS
                                                @endif
                                            </td>
                                            <td>{{ $alert->time }}</td>
                                            <td>
                                                @if($alert->monday) lun, @endif
                                                @if($alert->tuesday) mar, @endif
                                                @if($alert->wednesday) mie, @endif
                                                @if($alert->thursday) jue, @endif
                                                @if($alert->friday) vie, @endif
                                                @if($alert->saturday) sab, @endif
                                                @if($alert->sunday) dom, @endif
                                            </td>
                                            <td>
                                                <a href="{{ route('alerts.edit', $alert->id) }}">Editar</a>
                                                @if(Auth::user()->isA('super-admin'))
                                                    |
                                                    <a href="#" onclick="document.getElementById('form-active-{{$alert->id}}').submit()">
                                                        Dar de alta
                                                    </a>
                                                    <form action="{{route('alerts.active', $alert->id)}}" method="post" id="form-active-{{$alert->id}}">
                                                        {{ csrf_field() }}
                                                        {{ method_field('PUT') }}
                                                    </form>
                                                @endif
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection