routes/web.php
        'uses' => 'HomeController@getSubsidiaryUrl',
    ]);

    Route::put('customers/{id}/replace-wallet', 'CustomersController@replaceWallet');
    Route::get('customers/{id}/birthday', 'CustomersController@verifyBirthday');
    Route::get('customers/{id}/sendCourtesyCode', 'CustomersController@sendCourtesyCode');
    Route::get('customers/{id}/get', 'CustomersController@get');

    Route::post('customers/{id}/deactivate', [
        'as' => 'customers.deactivate',
        'uses' => 'CustomersController@deactivate',
    ]);

    Route::get('customers/byFilter', 'CustomersController@byFilter');

    Route::get('customers/excel', [
        'as' => 'customers.excel',
        'uses' => 'CustomersController@excel',
    ]);

    Route::resource('customers', 'CustomersController');

    Route::get('customer/packages/create', [
        'as' => 'customer.packages.create',
        'uses' => 'CustomerPackageController@create',
    ]);

    Route::post('customer/packages/store', [
        'as' => 'customer.packages.store',
        'uses' => 'CustomerPackageController@store',
    ]);

    Route::get('/packages/{id}/deleteProduct', [
        'as' => 'deleteProduct.packages',
        'uses' => 'PackagesController@destroyProduct',
    ]);

    Route::get('/packages/{id}/deleteService', [
        'as' => 'deleteService.packages',
        'uses' => 'PackagesController@destroyService',
    ]);

    Route::resource('packages', 'PackagesController');

    Route::resource('customers.referrals', 'CustomersReferralsController');

    Route::resource('deposits', 'DepositsController');

    Route::put('promotions/{id}/active', [
        'as' => 'promotions.active',
        'uses' => 'PromotionsController@active',
    ]);
    Route::post('promotions/updatePromotionServices', [
        'as' => 'promotions.update_promotion_services',
        'uses' => 'PromotionsController@updatePromotionServices',
    ]);
    Route::post('promotions/updatePromotionProducts', [
        'as' => 'promotions.update_promotion_products',
        'uses' => 'PromotionsController@updatePromotionProducts',
    ]);
    Route::resource('promotions', 'PromotionsController', ['except' => ['show']]);

    Route::get('inventories', [
        'as' => 'inventories.index',
        'uses' => 'InventoriesController@index',
    ]);

    Route::get('inventories/activos-insumos', [
        'as' => 'inventories.activos.insumos',
        'uses' => 'InventoriesActivesController@index',
    ]);

    Route::get('inventories/activos-insumos/create', [
        'as' => 'inventories.activos.insumos.create',
        'uses' => 'InventoriesActivesController@create',
    ]);

    Route::post('inventories/activos-insumos', [
        'as' => 'inventories.activos.insumos.post',
        'uses' => 'InventoriesActivesController@store',
    ]);

    Route::get('inventories/activos-insumos/{id}/edit', [
        'as' => 'inventories.activos.insumos.edit',
        'uses' => 'InventoriesActivesController@edit',
    ]);

    Route::post('inventories/activos-insumos/{id}', [
        'as' => 'inventories.activos.insumos.update',
        'uses' => 'InventoriesActivesController@update',
    ]);

    Route::get('inventories/activos-insumos/{kardex_type}/{folio}/{type}', [
        'as' => 'inventories.insumos.ticket',
        'uses' => 'InventoriesActivesController@show',
    ]);

    Route::resource('articles', 'ArticlesController');

    Route::get('inventories/warehouse/adjustments', [
        'as' => 'home.inventories.warehouse.adjustments.index',
        'uses' => 'InventoriesController@indexWarehouseAdjustments',
    ]);
    Route::get('inventories/warehouse/adjustments/create', [
        'as' => 'home.inventories.warehouse.adjustments.create',
        'uses' => 'InventoriesController@createWarehouseAdjustment',
    ]);
    Route::get('inventories/warehouse/adjustments/{folio}/print', [
        'as' => 'home.inventories.warehouse.adjustments.print',
        'uses' => 'InventoriesController@printWarehouseAdjustment',
    ]);
    Route::post('inventories/warehouse/adjustments/store', [
        'as' => 'home.inventories.warehouse.adjustments.store',
        'uses' => 'InventoriesController@storeWarehouseAdjustment',
    ]);

    Route::get('inventories/{type}/{folio}/{subsidiary_id}', [
        'as' => 'inventories.ticket',
        'uses' => 'InventoriesController@show',
    ]);

    Route::get('api/products/{key}', 'ProductsController@getByKey');
    Route::get('api/warehouse/products/{code}', 'WarehouseProductsController@getByCode');
    Route::get('api/articles/{key}', 'ArticlesController@getByKey');
    Route::resource('products', 'ProductsController');
    Route::resource('services', 'ServicesController');
    Route::post('services/updateSubsidiaryPrices', [
        'as' => 'services.update_subsidiary_prices',
        'uses' => 'ServicesController@updateSubsidiaryPrices',
    ]);
    Route::post('products/updateSubsidiaryPrices', [
        'as' => 'products.update_subsidiary_prices',
        'uses' => 'ProductsController@updateSubsidiaryPrices',
    ]);

    Route::resource('subsidiaries', 'SubsidiariesController');
    Route::resource('subsidiaries.turns', 'SubsidiariesTurnsController');
    Route::post('subsidiaries/{id}/users', [
        'as' => 'subsidiaries.users',
        'uses' => 'SubsidiariesController@asignUsers',
    ]);
    Route::post('subsidiaries/{id}/employees', [
        'as' => 'subsidiaries.employees',
        'uses' => 'SubsidiariesController@asignEmployees',
    ]);

    Route::post('employees/signin', [
        'as' => 'employees.verify.sign',
        'uses' => 'EmployeesController@show',
    ]);
    Route::put('employees/{id}/doctos', [
        'as' => 'employees.upload.documents',
        'uses' => 'EmployeesController@addDocuments',
    ]);
    Route::get('employees/{id}/contrato', [
        'as' => 'employees.contrato',
        'uses' => 'EmployeesController@contrato',
    ]);
    Route::put('employees/{id}/active', [
        'as' => 'employees.active',
        'uses' => 'EmployeesController@active',
    ]);

    Route::put('products/{id}/active', [
        'as' => 'products.active',
        'uses' => 'ProductsController@active',
    ]);

    Route::resource('alerts', 'AlertsController', ['except' => ['show']]);
    Route::get('alerts/today', [
        'as' => 'alerts.todayAlerts',
        'uses' => 'AlertsController@todayAlerts',
    ]);
    Route::put('alerts/{id}/active', [
        'as' => 'alerts.active',
        'uses' => 'AlertsController@active',
    ]);

    Route::resource('employees', 'EmployeesController', ['except' => ['show']]);

    Route::get('employees/{employee_request_id}/from-request', [
        'as' => 'employees.from-request',
        'uses' => 'EmployeesController@createFromRequest',
    ]);

    Route::get('employees/{id}/schedules/print', [
        'as' => 'employees.schedules.print',
        'uses' => 'EmployeesSchedulesController@print',
    ]);

    Route::resource('employees.schedules', 'EmployeesSchedulesController');
    Route::resource('employees.exchanges', 'ScheduleExchangesController');

    Route::post('exchanges/{id}/authorizee', [
        'as' => 'employees.exchanges.authorizee',
        'uses' => 'ScheduleExchangesController@authorizee',
    ]);
    Route::post('exchanges/{id}/unauthorize', [
        'as' => 'employees.exchanges.unauthorize',
        'uses' => 'ScheduleExchangesController@unauthorize',
    ]);
    Route::post('exchanges/{id}/authorizeadmin', [
        'as' => 'employees.exchanges.authorizeadmin',
        'uses' => 'ScheduleExchangesController@authorizeadmin',
    ]);
    Route::post('exchanges/{id}/unauthorizeadmin', [
        'as' => 'employees.exchanges.unauthorizeadmin',
        'uses' => 'ScheduleExchangesController@unauthorizeadmin',
    ]);

    Route::post('exchanges.unauthorize','ScheduleExchangesController@unauthorize');

    Route::post('employees/signin', [
        'as' => 'employees.verify.sign',
        'uses' => 'EmployeesController@show',
    ]);

    Route::resource('employees.disabilities', 'EmployeesDisabilitiesController');
    Route::resource('employees.issues', 'EmployeesIssuesController');

    Route::delete('/images/{id}', [
        'as' => 'destroy.images',
        'uses' => 'ImagesController@destroy',
    ]);

    Route::put('/schedules/{id}/unlock', [
        'as' => 'employees.schedules.unlock',
        'uses' => 'EmployeesSchedulesController@unLock',
    ]);

    Route::resource('users', 'UsersController');
    Route::resource('configurations', 'ConfigurationController');

    Route::get('configuration/{id}/edit', [
        'as' => 'admin.configurations.edit',
        'uses' => 'ConfigurationController@edit',
    ]);

    Route::get('configuration/create', [
        'as' => 'admin.configurations.create',
        'uses' => 'ConfigurationController@Create',
    ]);

    Route::get('paysheets/{key}/archive', 'PaysheetsController@archive');
    Route::get('paysheets/{key}/export/original', 'PaysheetsController@original');
    Route::get('paysheets/{key}/export/nomina', 'PaysheetsController@nomina');
    Route::get('paysheets/{key}/export/banco', 'PaysheetsController@banco');
    Route::put('paysheets/{id}/refresh', [
        'as' => 'paysheets.refresh',
        'uses' => 'PaysheetsController@refresh'
    ]);
    Route::post('paysheets/updateById', 'PaysheetsController@updateById');
    Route::post('paysheets/archiveById', 'PaysheetsController@archiveById');
    Route::resource('paysheets', 'PaysheetsController');

    Route::get('configuration/addRate', [
        'as' => 'configuration.rate.create',
        'uses' => 'ConfigurationController@createRate'
    ]);
    Route::post('configurations/rates', 'ConfigurationController@storeRate');
    Route::get('configurations/createJob', 'ConfigurationController@createJob');
    Route::post('configurations/jobs', 'ConfigurationController@storeJob');
    Route::get('configurations/turns', 'ConfigurationController@createTurn');

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    protected $fillable = [
        'key', 'name', 'type', 'buy_price'
    ];

    public function scopeActives($query)
    {
        return $query->where('type', 'activo');
    }

    public function scopeInsumos($query)
    {
        return $query->where('type', 'insumo');
    }

    public function subsidiaries()
    {
        return $this->belongsToMany(Subsidiary::class)->withPivot('existence');
    }
}

app/Http/Controllers/ArticlesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use App\Article;
use App\Subsidiary;
use Illuminate\Http\Request;

class ArticlesController extends Controller
{
    public function index()
    {
        $articles = Article::where('type', request('type', 'activo'))->get();

        return view('admin.articles.index', compact('articles'));
    }

    public function create()
    {
        return view('admin.articles.create');
    }

    public function store(Request $request)
    {
        $data = $request->all();
        $article = Article::create($data);
        
        $request->session()->flash('success', 'Articulo dado de alta con exito.');
        return redirect()->route('articles.edit', $article->id);
    }

    public function edit(Request $request, $id)
    {
        $article = Article::find($id);
        return view('admin.articles.edit', compact('article'));
    }

    public function update(Request $request, $id)
    {
        $data = $request->all();
        $article = Article::find($id);
        $article->update($data);
        $request->session()->flash('success', 'Articulo actualizado con exito.');
        return redirect()->route('articles.edit', $article->id);
    }

    public function getByKey($key)
    {
        $article = Article::whereKey($key)->first();
        if ($article) {
            $article->existence = 0;
            if (request()->has('subsidiary_id')) {
                $subsidiary = Subsidiary::find(request('subsidiary_id'));
                $article_sub = $subsidiary->articles()->whereKey($key)->first();
                if ($article_sub) {
                    $article->existence = $article_sub->pivot->existence;
                }
            }
            return response()->json([
                'success' => true,
                'article' => $article,
            ]);
        }

        return response()->json([
            'success' => false,
            'message' => 'No encontramos ni un articulo con esta clave.',
        ], 404);
        
    }
}

resources/views/admin/articles/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-9">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Articulos
                    <p class="pull-right help-block">Campos con * son obligatorios.</p>
                </div>

                <div class="panel-body">
                    <div class="">
                        <div class="">
                            <form action="{{route('articles.store')}}" method="POST" enctype="multipart/form-data" class="form-horizontal">
                                {{{ csrf_field() }}}
                                <div class="form-group">
                                    <label for="key" class="col-sm-4 control-label">Codigo *</label>
                                    <div class="col-sm-6">
                                      <input type="text" class="form-control" id="key" name="key" required="required" value="{{ old('key') }}">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="name" class="col-sm-4 control-label">Nombre *</label>
                                    <div class="col-sm-6">
                                      <input type="text" class="form-control" id="name" name="name" required="required" value="{{ old('name') }}">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="buy_price" class="col-sm-4 control-label">Precio de compra *</label>
                                    <div class="col-sm-6">
                                      <input type="text" class="form-control" id="buy_price" name="buy_price" value="{{ old('buy_price', 0) }}">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="type" class="col-sm-4 control-label">Tipo *</label>
                                    <div class="col-sm-6">
                                        <select name="type" id="type" class="form-control" required>
                                            <option value="activo">Activo</option>
                                            <option value="insumo">Insumo</option>
                                        </select>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-sm-offset-4 col-sm-6">
                                        <button type="submit" class="btn btn-default">Guardar</button>
                                    </div>
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/articles/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-9">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Articulos
                    <p class="pull-right help-block">Campos con * son obligatorios.</p>
                </div>

                <div class="panel-body">
                    <div class="">
                        <div class="">
                            <form action="{{route('articles.update', $article->id)}}" method="POST" enctype="multipart/form-data" class="form-horizontal">
                                {{{ csrf_field() }}}
                                {{{ method_field('put') }}}
                                <div class="form-group">
                                    <label for="key" class="col-sm-4 control-label">Codigo *</label>
                                    <div class="col-sm-6">
                                      <input type="text" class="form-control" id="key" name="key" required="required" value="{{ old('key', $article->key) }}">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="name" class="col-sm-4 control-label">Nombre *</label>
                                    <div class="col-sm-6">
                                      <input type="text" class="form-control" id="name" name="name" required="required" value="{{ old('name', $article->name) }}">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="buy_price" class="col-sm-4 control-label">Precio de compra *</label>
                                    <div class="col-sm-6">
                                      <input type="text" class="form-control" id="buy_price" name="buy_price" value="{{ old('buy_price', $article->buy_price) }}">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="type" class="col-sm-4 control-label">Tipo *</label>
                                    <div class="col-sm-6">
                                        <select name="type" id="type" class="form-control" required>
                                            <option @if($article->type == 'activo') selected="selected" @endif value="activo">Activo</option>
                                            <option @if($article->type == 'insumo') selected="selected" @endif value="insumo">Insumo</option>
                                        </select>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-sm-offset-4 col-sm-6">
                                        <button type="submit" class="btn btn-default">Guardar</button>
                                    </div>
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/articles/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="panel panel-default">
                <div class="panel-heading">Menu</div>

                <div class="panel-body">
                    <ul class="list-unstyled">
                        <li><a href="{{route('articles.index', ["type" => 'insumo'])}}">Insumos</a></li>
                        <li><a href="{{route('articles.index', ["type" => 'activo'])}}">Activos</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-9">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Articulos
                    <p class="pull-right">
                        <a href="{{ route('articles.create') }}">Agregar</a>
                    </p>
                </div>

                <div class="panel-body">
                    <table class="table datatables">
                        <thead>
                            <tr>
                                <th>Key</th>
                                <th>Name</th>
                                <th>Precio compra</th>
                                <th>opcion</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($articles as $article)
                                <tr>
                                    <td>{{$article->key}}</td>
                                    <td>{{$article->name}}</td>
                                    <td>{{$article->buy_price}}</td>
                                    <td>
                                        <a href="{{ route('articles.edit', $article->id) }}">Editar</a>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection