routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

Route::get('/', function () {
    return view('welcome');
});

Route::get('ticket/{sale_id}', [
    'as' => 'sale.print_customer',
    'uses' => 'SalesController@printCustomer',
]);

Route::post('ticket/send',[
    'as' => 'sale.send_ticket',
    'uses' => 'SalesController@sendTicket',
]);

Route::any('employees/reg/process', [
    'as' => 'employees.reg.process',
    'uses' => 'FingersController@registerProcess',
]);

Route::any('employees/reg/getac', [
    'as' => 'employees.reg.getac',
    'uses' => 'FingersController@getac',
]);

Route::any('employees/reg/register', [
    'as' => 'employees.reg.register',
    'uses' => 'FingersController@register',
]);

Route::any('employees/reg/validate', [
    'as' => 'employees.reg.validate',
    'uses' => 'FingersController@validat',
]);

Route::any('employees/validate/process', [
    'as' => 'employees.validate.process',
    'uses' => 'AttendanceController@storeDevice',
]);

Route::get('currentSales', [
        'as' => 'admin.sales.currentSales',
        'uses' => 'SalesController@currentSales',
    ]);
Route::get('complains/{id}/show', [
        'as' => 'complains.show',
        'uses' => 'ComplainsController@show',
    ]);

// Access to super-admin user only
Route::group([
    'middleware' => 'roles:super-admin',
], function () {
    Route::get('citas', [
        'as' => 'diaries.createCustomer',
        'uses' => 'DiaryController@createCustomer',
    ]);
    Route::post('citas', [
        'as' => 'diaries.storeCustomer',
        'uses' => 'DiaryController@storeCustomer',
    ]);
});

Route::get('solicitar-factura/{sale_id?}', [
    'as' => 'facturas.createCustomer',
    'uses' => 'SaleFacturaRequestController@createCustomer',
]);
Route::post('solicitar-factura', [
    'as' => 'facturas.storeCustomer',
    'uses' => 'SaleFacturaRequestController@storeCustomer',
]);

Route::get('solicitar-empleo', [
    'as' => 'employee-requests.createCustomer',
    'uses' => 'EmployeeRequestController@createCustomer',
]);
Route::post('solicitar-empleo', [
    'as' => 'employee-requests.storeCustomer',
    'uses' => 'EmployeeRequestController@storeCustomer',
]);

Route::get('search/timesCustomer', 'DiaryController@searchCustomer');

Route::post('sugerencias', [
    'as' => 'complains.store2',
    'uses' => 'ComplainsController@store2',
]);

Auth::routes();

if (isset($_SERVER['HTTP_HOST'])) {
    $url = $_SERVER['HTTP_HOST'];
    $array = explode(".", $_SERVER['HTTP_HOST']);
    $domain = substr ($url,strpos($url,".")+1);
} else {
    $domain = env('DOMAIN');
}

//$domain = env('DOMAIN');

Route::group([
    'domain' => "{subsidiary_code}." . $domain,
], function () {

    Route::get('/log', [
        'as' => 'home.sucursal.login',
        'uses' => 'HomeController@authSubsidiaryAsSuperUser',
    ]);
});

Route::group([
    'middleware' => ['auth','timezone'],
    'prefix' => 'home',
], function () {
    //$domain = env('DOMAIN');

    if (isset($_SERVER['HTTP_HOST'])) {
        $url = $_SERVER['HTTP_HOST'];
        $array = explode(".", $_SERVER['HTTP_HOST']);
        $domain = substr ($url,strpos($url,".")+1);
    } else {
        $domain = env('DOMAIN');
    }

    // Routes that doesn't need an specific role to have access
    Route::get('/', 'HomeController@index');
    Route::get('/diary/next', 'DiaryController@next');

    // Resources included
    Route::resource('diary', 'DiaryController');
    Route::resource('expenditures', 'ExpendituresController');
    Route::resource('accounts', 'AccountsController');
    Route::resource('exchanges', 'ScheduleExchangesController');
    Route::resource('complains', 'ComplainsController');
    Route::resource('facturas', 'SaleFacturaRequestController');
    Route::resource('employee-requests', 'EmployeeRequestController');

    // Access to super-admin user only
    Route::group([
        'middleware' => 'roles:super-admin',
    ], function () {
        Route::get('/testMessage', 'HomeController@testMessage');
        Route::get('/testNexmoMessage', 'HomeController@testNexmoMessage');
        Route::get('/infoo', 'HomeController@infoo');
    });

    Route::put('/diary/{id}/read', 'DiaryController@markAsRead');

    Route::get('activeSales', [
        'as' => 'admin.sales.activeSales',
        'uses' => 'SalesController@activeSales',
    ]);

    Route::get('/laundry-services/create2', [
        'as' => 'laundry-services.create2',
        'uses' => 'LaundryServicesController@create2',
    ]);

    Route::get('laundry-services/{id}/print', [
            'as' => 'laundry-services.print',
            'uses' => 'LaundryServicesController@print',
        ]);

    Route::get('laundry-services/{id}/cancel', [
            'as' => 'laundry-services.cancel',
            'uses' => 'LaundryServicesController@cancel',
        ]);

    Route::get('laundry-services/{folio}/search/{subsidiary_id}', [
            'as' => 'laundry-services.search',
            'uses' => 'LaundryServicesController@search',
        ]);

    Route::post('/laundry-services/store-previous', [
        'as' => 'laundry-services.store-previous',
        'uses' => 'LaundryServicesController@store2',
    ]);

    Route::get('warehouse/products/adjustMustHaves', [
        'as' => 'warehouse.products.adjust-must-haves',
        'uses' => 'WarehouseProductsController@adjustMustHaves',
    ]);

    Route::post('warehouse/products/storeMustHaves', [
        'as' => 'warehouse.products.storeMustHaves',
        'uses' => 'WarehouseProductsController@storeMustHaves',
    ]);

    Route::get('warehouse/movements', [
        'as' => 'warehouse.movements.index',
        'uses' => 'WarehouseMovementsController@index',
    ]);

    Route::get('warehouse/movements/create-missing-expenditures', [
        'as' => 'warehouse.movements.create-missing-expenditures',
        'uses' => 'WarehouseMovementsController@createMissingExpenditures',
    ]);

    Route::get('warehouse/movements/{id}/create', [
        'as' => 'warehouse.movements.create',
        'uses' => 'WarehouseMovementsController@create',
    ]);

    Route::post('warehouse/movements/store', [
        'as' => 'warehouse.movements.store',
        'uses' => 'WarehouseMovementsController@store',
    ]);

    Route::get('warehouse/movements/createEntry', [
        'as' => 'warehouse.movements.createEntry',
        'uses' => 'WarehouseMovementsController@createEntry',
    ]);

    Route::post('warehouse/movements/storeEntry', [
        'as' => 'warehouse.movements.storeEntry',
        'uses' => 'WarehouseMovementsController@storeEntry',
    ]);

    Route::post('warehouse/movements/storeEntry2', [
        'as' => 'warehouse.movements.storeEntry2',
        'uses' => 'WarehouseMovementsController@storeEntry2',
    ]);

    Route::get('warehouse/movements/{id}/editEntry', [
            'as' => 'warehouse.movements.editEntry',
            'uses' => 'WarehouseMovementsController@editEntry',
        ]);
        Route::post('warehouse/movements/{id}/updateEntry', [
            'as' => 'warehouse.movements.updateEntry',
            'uses' => 'WarehouseMovementsController@updateEntry',
        ]);

    Route::get('warehouse/movements/{id}/edit', [
        'as' => 'warehouse.movements.edit',
        'uses' => 'WarehouseMovementsController@edit',
    ]);

    Route::post('warehouse/movements/{id}/update', [
        'as' => 'warehouse.movements.update',
        'uses' => 'WarehouseMovementsController@update',
    ]);

    Route::get('warehouse/movements/{id}/confirm', [
        'as' => 'warehouse.movements.confirm',
        'uses' => 'WarehouseMovementsController@confirm',
    ]);

    Route::post('warehouse/movements/{id}/updateConfirm', [
        'as' => 'warehouse.movements.updateConfirm',
        'uses' => 'WarehouseMovementsController@updateConfirm',
    ]);

    Route::get('warehouse/movements/{id}/print', [
        'as' => 'warehouse.movements.print',
        'uses' => 'WarehouseMovementsController@print',
    ]);

    Route::get('warehouse/movements/{id}/printUnsupplied', [
        'as' => 'warehouse.movements.print-unsupplied',
        'uses' => 'WarehouseMovementsController@printUnsupplied',
    ]);

    Route::get('warehouse/movements/{id}/printSubsidiary', [
        'as' => 'warehouse.movements.printSubsidiary',
        'uses' => 'WarehouseMovementsController@printSubsidiary',
    ]);

    Route::get('warehouse/movements/{id}/show', [
        'as' => 'warehouse.movements.show',
        'uses' => 'WarehouseMovementsController@show',
    ]);

    Route::delete('delete/movements/{id}', [
        'as' => 'warehouse.movements.destroy',
        'uses' => 'WarehouseMovementsController@destroy',
    ]);

    Route::get('/warehouse/movements/{id}/destroyProduct', [
        'as' => 'warehouse.movements.destroyProduct',
        'uses' => 'WarehouseMovementsController@destroyProduct',
    ]);

    Route::get('warehouse/products', [
        'as' => 'warehouse.products.index',
        'uses' => 'WarehouseProductsController@index',
    ]);

    Route::get('warehouse/products/create', [
        'as' => 'warehouse.products.create',
        'uses' => 'WarehouseProductsController@create',
    ]);

    Route::post('warehouse/products/store', [
        'as' => 'warehouse.products.store',
        'uses' => 'WarehouseProductsController@store',
    ]);

    Route::get('warehouse/products/{id}/edit', [
        'as' => 'warehouse.products.edit',
        'uses' => 'WarehouseProductsController@edit',
    ]);

    Route::post('warehouse/products/{id}/update', [
        'as' => 'warehouse.products.update',
        'uses' => 'WarehouseProductsController@update',
    ]);

    Route::delete('delete/warehouse/products/{id}', [
        'as' => 'warehouse.product.destroy',
        'uses' => 'WarehouseProductsController@destroy',
    ]);

    Route::get('warehouse/requests', [
        'as' => 'warehouse.requests.index',
        'uses' => 'WarehouseRequestsController@index',
    ]);

resources/views/admin/factura-requests/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-3">
            
        </div>
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Realizar solicitud de factura
                    <p class="pull-right help-block">Campos con * son obligatorios.</p>
                </div>

                <div class="panel-body">
                    <div class="">
                        <div class="">
                            <form action="{{route('facturas.store')}}" method="POST" enctype="multipart/form-data" class="form-horizontal">
                                {{{ csrf_field() }}}
                                <div class="form-group">
                                    <label for="key" class="col-sm-4 control-label">Fecha del incidente *</label>
                                    <div class="col-sm-6">
                                        <input type="text" class="form-control datepicker" id="date" name="date" required="required" value="{{ old('date') }}">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="name" class="col-sm-4 control-label">Nombre *</label>
                                    <div class="col-sm-6">
                                        <input type="text" class="form-control" id="name" name="name" required="required" value="{{ old('name') }}">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="name" class="col-sm-4 control-label">Teléfono</label>
                                    <div class="col-sm-6">
                                        <input type="number" class="form-control" id="phone" name="phone" value="{{ old('phone') }}">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="name" class="col-sm-4 control-label">Motivo *</label>
                                    <div class="col-sm-6">
                                        <textarea class="form-control" rows="4" id="reason" name="reason">{{ old('reason') }}</textarea>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="name" class="col-sm-4 control-label">Folio</label>
                                    <div class="col-sm-6">
                                        <input type="text" class="form-control" id="folio" name="folio" value="{{ old('folio') }}">
                                    </div>
                                </div>

                                @if(Auth::user()->isA('super-admin'))
                                <div class="form-group">
                                    <label for="name" class="col-sm-4 control-label">Seguimiento</label>
                                    <div class="col-sm-6">
                                        <input type="text" class="form-control" id="tracing" name="tracing" value="{{ old('tracing') }}">
                                    </div>
                                </div>
                                @endif
                                <div class="form-group">
                                    <div class="col-sm-offset-4 col-sm-6">
                                        <button type="submit" class="btn btn-default">Guardar</button>
                                    </div>
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/factura-requests/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">Solicitudes de facturas</div>

                    <div class="panel-body">
                        <a href="/solicitar-factura">Agregar solicitud</a>
                        <table class="table datatables">
                            <thead>
                                <tr>
                                    <th>Fecha de solicitud</th>
                                    <th>Fecha de ticket</th>
                                    <th>Ticket</th>
                                    <th>Sucursal</th>
                                    <th>Estatus</th>
                                    <th>Constancia</th>
                                    @if(Auth::user()->isA('super-admin'))
                                    <th>Acciones</th>
                                    @endif
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($factura_requests as $factura_request)
                                    @php
                                        $sale = $factura_request->sale;
                                        $subsidiary = $sale->subsidiary;
                                    @endphp
                                    <tr>
                                        <td>{{ $factura_request->created_at }}</td>
                                        <td>{{ $factura_request->folio_date }}</td>
                                        <td>
                                            @if($sale)
                                            <a href="{{route('sales.print.admin', [$subsidiary->key, $sale->id])}}" target="_blank">
                                                {{ $subsidiary->key }}-{{ $sale->folio }}
                                            </a>
                                            @endif
                                        </td>
                                        <td>
                                            @if($subsidiary)
                                                {{ $subsidiary->name }}
                                            @endif
                                        </td>
                                        <td>
                                            @php
                                                $status = $factura_request->status;
                                                switch ($status) {
                                                    case 'pendiente':
                                                        $status_class = 'label label-warning';
                                                        break;
                                                    case 'en proceso':
                                                        $status_class = 'label label-success';
                                                        break;
                                                    case 'finalizado':
                                                        $status_class = 'label label-danger';
                                                        break;
                                                    default:
                                                        $status_class = 'label label-warning';
                                                        break;
                                                }
                                            @endphp
                                            <span class="{{ $status_class }}">{{ strtoupper($status) }}</span>
                                        </td>
                                        <td>
                                            @if($factura_request->image)
                                                <a href="{{ $factura_request->image->path }}">Ver archivo</a>
                                            @endif
                                        </td>
                                        @if(Auth::user()->isA('super-admin'))
                                        <td class="row" style="width: 80px !important;">
                                            <div class="col-sm-6 index-edit-button-container">
                                                <a href="{{ route('facturas.edit', $factura_request->id) }}" class="btn btn-link index-edit-button">
                                                    <i class="fa fa-pencil-square-o fa-2x"></i>
                                                </a>
                                            </div>

                                            @if(Auth::user()->isA('super-admin'))
                                            <div class="col-sm-6 index-delete-button-container">
                                                <form action="{{route('facturas.destroy', $factura_request->id)}}" method="post" class="">
                                                    {{{csrf_field()}}}
                                                    {{{method_field('DELETE')}}}
                                                    <button type="submit" class="btn btn-link index-delete-button">
                                                        <i class="fa fa-times fa-2x"></i>
                                                    </button>
                                                </form>
                                            </div>
                                            @endif
                                        </td>
                                        @endif
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/factura-requests/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-3">
            
        </div>
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Quejas y sugerencias
                    <p class="pull-right help-block">Campos con * son obligatorios.</p>
                </div>

                <div class="panel-body">
                    <div class="">
                        <div class="">

                                <div class="form-group">
                                    <label for="key" class="col-sm-4 control-label">Fecha del incidente *</label>
                                    <div class="col-sm-6">
                                      <input type="text" class="form-control datepicker" id="date" name="date" required="required" value="{{ $complain->date }}" disabled>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="name" class="col-sm-4 control-label">Nombre *</label>
                                    <div class="col-sm-6">
                                      <input type="text" class="form-control" id="name" name="name" required="required" value="{{ $complain->name }}" disabled>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="name" class="col-sm-4 control-label">Teléfono</label>
                                    <div class="col-sm-6">
                                      <input type="number" class="form-control" id="phone" name="phone" value="{{ $complain->phone }}" disabled>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="name" class="col-sm-4 control-label">Motivo *</label>
                                    <div class="col-sm-6">
                                      <textarea class="form-control" rows="8" id="reason" name="reason" disabled>{{ $complain->reason }}</textarea>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="name" class="col-sm-4 control-label">Folio</label>
                                    <div class="col-sm-6">
                                      <input type="text" class="form-control" id="folio" name="folio" value="{{ $folio }}" disabled>
                                    </div>
                                </div>

                                @if(Auth::user()->isA('super-admin'))
                                <div class="form-group">
                                    <label for="name" class="col-sm-4 control-label">Seguimiento</label>
                                    <div class="col-sm-6">
                                      <input type="text" class="form-control" id="tracing" name="tracing" value="{{ $complain->tracing }}" disabled>
                                    </div>
                                </div>
                                @endif
                                
                                <div class="form-group">
                                    <div class="col-sm-offset-4 col-sm-6">
                                        <a class="btn btn-primary" href="{{route('complains.index')}}">Regresar</a>
                                    </div>
                                </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection