routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

Route::get('/', function () {
    return view('welcome');
});

Route::get('ticket/{sale_id}', [
    'as' => 'sale.print_customer',
    'uses' => 'SalesController@printCustomer',
]);

Route::post('ticket/send',[
    'as' => 'sale.send_ticket',
    'uses' => 'SalesController@sendTicket',
]);

Route::any('employees/reg/process', [
    'as' => 'employees.reg.process',
    'uses' => 'FingersController@registerProcess',
]);

Route::any('employees/reg/getac', [
    'as' => 'employees.reg.getac',
    'uses' => 'FingersController@getac',
]);

Route::any('employees/reg/register', [
    'as' => 'employees.reg.register',
    'uses' => 'FingersController@register',
]);

Route::any('employees/reg/validate', [
    'as' => 'employees.reg.validate',
    'uses' => 'FingersController@validat',
]);

Route::any('employees/validate/process', [
    'as' => 'employees.validate.process',
    'uses' => 'AttendanceController@storeDevice',
]);

Route::get('currentSales', [
        'as' => 'admin.sales.currentSales',
        'uses' => 'SalesController@currentSales',
    ]);
Route::get('complains/{id}/show', [
        'as' => 'complains.show',
        'uses' => 'ComplainsController@show',
    ]);

// Access to super-admin user only
Route::group([
    'middleware' => 'roles:super-admin',
], function () {
    Route::get('citas', [
        'as' => 'diaries.createCustomer',
        'uses' => 'DiaryController@createCustomer',
    ]);
    Route::post('citas', [
        'as' => 'diaries.storeCustomer',
        'uses' => 'DiaryController@storeCustomer',
    ]);
});

Route::get('solicitar-factura/{sale_id?}', [
    'as' => 'facturas.createCustomer',
    'uses' => 'SaleFacturaRequestController@createCustomer',
]);
Route::post('solicitar-factura', [
    'as' => 'facturas.storeCustomer',
    'uses' => 'SaleFacturaRequestController@storeCustomer',
]);

Route::get('solicitar-empleo', [
    'as' => 'employee-requests.createCustomer',
    'uses' => 'EmployeeRequestController@createCustomer',
]);
Route::post('solicitar-empleo', [
    'as' => 'employee-requests.storeCustomer',
    'uses' => 'EmployeeRequestController@storeCustomer',
]);

Route::get('search/timesCustomer', 'DiaryController@searchCustomer');

Route::post('sugerencias', [
    'as' => 'complains.store2',
    'uses' => 'ComplainsController@store2',
]);

Auth::routes();

if (isset($_SERVER['HTTP_HOST'])) {
    $url = $_SERVER['HTTP_HOST'];
    $array = explode(".", $_SERVER['HTTP_HOST']);
    $domain = substr ($url,strpos($url,".")+1);
} else {
    $domain = env('DOMAIN');
}

//$domain = env('DOMAIN');

Route::group([
    'domain' => "{subsidiary_code}." . $domain,
], function () {

    Route::get('/log', [
        'as' => 'home.sucursal.login',
        'uses' => 'HomeController@authSubsidiaryAsSuperUser',
    ]);
});

Route::group([
    'middleware' => ['auth','timezone'],
    'prefix' => 'home',
], function () {
    //$domain = env('DOMAIN');

    if (isset($_SERVER['HTTP_HOST'])) {
        $url = $_SERVER['HTTP_HOST'];
        $array = explode(".", $_SERVER['HTTP_HOST']);
        $domain = substr ($url,strpos($url,".")+1);
    } else {
        $domain = env('DOMAIN');
    }

    // Routes that doesn't need an specific role to have access
    Route::get('/', 'HomeController@index');
    Route::get('/diary/next', 'DiaryController@next');

    // Resources included
    Route::resource('diary', 'DiaryController');
    Route::resource('expenditures', 'ExpendituresController');
    Route::resource('accounts', 'AccountsController');
    Route::resource('exchanges', 'ScheduleExchangesController');
    Route::resource('complains', 'ComplainsController');
    Route::resource('facturas', 'SaleFacturaRequestController');
    Route::resource('employee-requests', 'EmployeeRequestController');

    // Access to super-admin user only
    Route::group([
        'middleware' => 'roles:super-admin',
    ], function () {
        Route::get('/testMessage', 'HomeController@testMessage');
        Route::get('/testNexmoMessage', 'HomeController@testNexmoMessage');
        Route::get('/infoo', 'HomeController@infoo');
    });

    Route::put('/diary/{id}/read', 'DiaryController@markAsRead');

    Route::get('activeSales', [
        'as' => 'admin.sales.activeSales',
        'uses' => 'SalesController@activeSales',
    ]);

    Route::get('/laundry-services/create2', [
        'as' => 'laundry-services.create2',
        'uses' => 'LaundryServicesController@create2',
    ]);

    Route::get('laundry-services/{id}/print', [
            'as' => 'laundry-services.print',
            'uses' => 'LaundryServicesController@print',
        ]);

    Route::get('laundry-services/{id}/cancel', [
            'as' => 'laundry-services.cancel',
            'uses' => 'LaundryServicesController@cancel',
        ]);

    Route::get('laundry-services/{folio}/search/{subsidiary_id}', [
            'as' => 'laundry-services.search',
            'uses' => 'LaundryServicesController@search',
        ]);

    Route::post('/laundry-services/store-previous', [
        'as' => 'laundry-services.store-previous',
        'uses' => 'LaundryServicesController@store2',
    ]);

    Route::get('warehouse/products/adjustMustHaves', [
        'as' => 'warehouse.products.adjust-must-haves',
        'uses' => 'WarehouseProductsController@adjustMustHaves',
    ]);

    Route::post('warehouse/products/storeMustHaves', [
        'as' => 'warehouse.products.storeMustHaves',
        'uses' => 'WarehouseProductsController@storeMustHaves',
    ]);

    Route::get('warehouse/movements', [
        'as' => 'warehouse.movements.index',
        'uses' => 'WarehouseMovementsController@index',
    ]);

    Route::get('warehouse/movements/create-missing-expenditures', [
        'as' => 'warehouse.movements.create-missing-expenditures',
        'uses' => 'WarehouseMovementsController@createMissingExpenditures',
    ]);

    Route::get('warehouse/movements/{id}/create', [
        'as' => 'warehouse.movements.create',
        'uses' => 'WarehouseMovementsController@create',
    ]);

    Route::post('warehouse/movements/store', [
        'as' => 'warehouse.movements.store',
        'uses' => 'WarehouseMovementsController@store',
    ]);

    Route::get('warehouse/movements/createEntry', [
        'as' => 'warehouse.movements.createEntry',
        'uses' => 'WarehouseMovementsController@createEntry',
    ]);

    Route::post('warehouse/movements/storeEntry', [
        'as' => 'warehouse.movements.storeEntry',
        'uses' => 'WarehouseMovementsController@storeEntry',
    ]);

    Route::post('warehouse/movements/storeEntry2', [
        'as' => 'warehouse.movements.storeEntry2',
        'uses' => 'WarehouseMovementsController@storeEntry2',
    ]);

    Route::get('warehouse/movements/{id}/editEntry', [
            'as' => 'warehouse.movements.editEntry',
            'uses' => 'WarehouseMovementsController@editEntry',
        ]);
        Route::post('warehouse/movements/{id}/updateEntry', [
            'as' => 'warehouse.movements.updateEntry',
            'uses' => 'WarehouseMovementsController@updateEntry',
        ]);

    Route::get('warehouse/movements/{id}/edit', [
        'as' => 'warehouse.movements.edit',
        'uses' => 'WarehouseMovementsController@edit',
    ]);

    Route::post('warehouse/movements/{id}/update', [
        'as' => 'warehouse.movements.update',
        'uses' => 'WarehouseMovementsController@update',
    ]);

    Route::get('warehouse/movements/{id}/confirm', [
        'as' => 'warehouse.movements.confirm',
        'uses' => 'WarehouseMovementsController@confirm',
    ]);

    Route::post('warehouse/movements/{id}/updateConfirm', [
        'as' => 'warehouse.movements.updateConfirm',
        'uses' => 'WarehouseMovementsController@updateConfirm',
    ]);

    Route::get('warehouse/movements/{id}/print', [
        'as' => 'warehouse.movements.print',
        'uses' => 'WarehouseMovementsController@print',
    ]);

    Route::get('warehouse/movements/{id}/printUnsupplied', [
        'as' => 'warehouse.movements.print-unsupplied',
        'uses' => 'WarehouseMovementsController@printUnsupplied',
    ]);

    Route::get('warehouse/movements/{id}/printSubsidiary', [
        'as' => 'warehouse.movements.printSubsidiary',
        'uses' => 'WarehouseMovementsController@printSubsidiary',
    ]);

    Route::get('warehouse/movements/{id}/show', [
        'as' => 'warehouse.movements.show',
        'uses' => 'WarehouseMovementsController@show',
    ]);

    Route::delete('delete/movements/{id}', [
        'as' => 'warehouse.movements.destroy',
        'uses' => 'WarehouseMovementsController@destroy',
    ]);

    Route::get('/warehouse/movements/{id}/destroyProduct', [
        'as' => 'warehouse.movements.destroyProduct',
        'uses' => 'WarehouseMovementsController@destroyProduct',
    ]);

    Route::get('warehouse/products', [
        'as' => 'warehouse.products.index',
        'uses' => 'WarehouseProductsController@index',
    ]);

    Route::get('warehouse/products/create', [
        'as' => 'warehouse.products.create',
        'uses' => 'WarehouseProductsController@create',
    ]);

    Route::post('warehouse/products/store', [
        'as' => 'warehouse.products.store',
        'uses' => 'WarehouseProductsController@store',
    ]);

    Route::get('warehouse/products/{id}/edit', [
        'as' => 'warehouse.products.edit',
        'uses' => 'WarehouseProductsController@edit',
    ]);

    Route::post('warehouse/products/{id}/update', [
        'as' => 'warehouse.products.update',
        'uses' => 'WarehouseProductsController@update',
    ]);

    Route::delete('delete/warehouse/products/{id}', [
        'as' => 'warehouse.product.destroy',
        'uses' => 'WarehouseProductsController@destroy',
    ]);

    Route::get('warehouse/requests', [
        'as' => 'warehouse.requests.index',
        'uses' => 'WarehouseRequestsController@index',
    ]);

app/Diary.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;

class Diary extends Model
{
    use Notifiable;
    protected $fillable = [
        'date', 'time', 'customer_id', 'subsidiary_id', 'employee_id', 'confirmation_code', 'folio', 
        'user_id', 'cashier_id', 'has_discount', 'comments', 'service_id', 'customer_name', 'phone',
        'email', 'suggested_customer_id', 'created_by_customer'
    ];

    public function customer()
    {
        return $this->belongsTo(Customer::class);
    }

    public function subsidiary()
    {
        return $this->belongsTo(Subsidiary::class);
    }

    public function employee()
    {
        return $this->belongsTo(Employee::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function service()
    {
        return $this->belongsTo(Service::class);
    }

    public function cashier()
    {
        return $this->belongsTo(Employee::class, 'cashier_id');
    }

    public function sale()
    {
        return $this->hasOne(Sale::class);
    }

    public function routeNotificationForNexmo()
    {
        return '52'.($this->customer ? $this->customer->phone : $this->phone);
    }

    public function scopeToday($query)
    {
        return $query->where('date', Carbon::now()->format('Y-m-d'));
    }

    public function scopeAfterCurrentTime($query)
    {
        $current = Carbon::now()->subMinutes(15);
        return $query->whereTime('time', '>=', $current->format('H:i:s'));   
    }

    public function scopeDate($query, $date)
    {
        return $query->where('date', $date);
    }

    public function scopeActive($query)
    {
        return $query->where('attend', false);
    }

    public function scopeIsAttend($query)
    {
        return $query->where('attend', true);
    }

    public function scopeCancel($query)
    {
        return $query->where('canceled', true);
    }

    public function scopeNotCancel($query)
    {
        return $query->where('canceled', false);
    }

    public function scopeRead($query, $bool = true)
    {
        return $query->where('read', $bool);
    }

    public function scopeDates($query, array $dates)
    {
        return $query->whereBetween('date', $dates);
    }

    public function scopeCallCenter($query)
    {
        return $query->where('has_discount',true);
    }

    public function scopeBySubsidiary($query, $subsidiary_id)
    {
        return $query->where('subsidiary_id', $subsidiary_id);
    }

    public function scopeFromNow($query)
    {
        return $query->where('date', '>=' , Carbon::now()->format('Y-m-d'));
    }
}

resources/views/admin/diaries/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Citas <small>Editar cita</small>
                    <p class="pull-right help-block">Campos con * son obligatorios.</p>
                </div>

                <div class="panel-body">
                    <form action="{{route('diary.update', $diary->id)}}" method="POST">
                        {{{ csrf_field() }}}
                        {{{ method_field('PUT') }}}

                        {{-- <input type="hidden" name="barber_id" v-model="barber_id" value="0"> --}}
                        <input type="hidden" name="time" v-model="time" value="{{$diary->time}}">

                        <div class="form-group">
                            <label for="customer_id" class="control-label">
                                Cliente *
                                @if(Auth::user()->isA('super-admin'))
                                    <a href="{{url('/home/customers/create?redirect='.route('diary.edit', $diary->id))}}" class="btn btn-xs btn-info">Nuevo cliente</a>
                                @endif
                            </label>
                            <select name="customer_id" id="customer_id" class="select2 form-control" required="required">
                                <option value="">Seleccionar uno por favor...</option>
                                @foreach($customers as $customer)
                                    <option @if($diary->customer_id == $customer->id) selected="selected" @endif value="{{$customer->id}}">{{$customer->name}}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="phone" class="control-label">Telefono *</label>
                            <input type="text" class="form-control" name="phone" id="phone" value="{{$diary->customer->phone}}">
                        </div>

                        <div class="form-group">
                            <label for="subsidiary_id" class="control-label">
                                Sucursal *
                            </label>
                            <input type="hidden" id="original_subsidiary_id" name="original_subsidiary_id" value="{{$diary->subsidiary_id}}">
                            <select name="subsidiary_id" id="subsidiary_id" class="form-control" required="required" v-model="subsidiary_id">
                                <option value="">Seleccionar uno por favor...</option>
                                @foreach($subsidiaries as $subsi)
                                    <option @if($diary->subsidiary_id == $subsi->id) selected="selected" @endif value="{{$subsi->id}}">{{$subsi->name}}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="date" class="control-label">Fecha *</label>
                            <input type="hidden" id="original_date" name="original_date" value="{{$diary->date}}">
                            <input type="hidden" id="date" name="date" v-model="dateFormatter(date)">
                            <input type="hidden" id="date2" name="date2" v-model="date">
                            <datepicker v-model="date" :format="dateFormatter" :bootstrap-styling="true" class=""></datepicker>
                        </div>

                        <div class="form-group">
                            <label for="service_id" class="control-label">
                                Servicio *
                            </label>
                            <select name="service_id" id="service_id" class="select2 form-control" required="required">
                                <option value="" selected>Seleccionar uno por favor...</option>
                                @foreach($services as $service)
                                    <option value="{{$service->id}}" @if($diary->service_id == $service->id) selected @endif>{{$service->name}}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="employee_id" class="control-label">
                                Barbero *
                            </label>
                            <select name="employee_id" id="barber_id" class="select2 form-control">
                                <option value="0">Seleccionar uno por favor...</option>
                                @if($diary->employee)
                                    <option selected="selected" value="{{$diary->employee->id}}">{{$diary->employee->short_name}}</option>
                                @endif
                            </select>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-6">
                                <button type="submit" class="btn btn-default" :disabled="!canCreateDiary">Guardar</button>
                            </div>
                            <div class="col-sm-6">
                                <button type="button" class="btn btn-primary" @click="searchTimes">Buscar</button>
                                <p class="text-red" v-if="time_error">@{{time_error}}</p>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="col-md-8">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Horas disponibles
                </div>
                <div class="panel-body" v-for="timess in times">
                    <button class="btn btn-default" :class="{active: time.active}" :disabled="time.disabled" v-for="time in timess" style="margin-left: 10px; margin-top: 10px;" @click="setTimeActive(time)">@{{time.time_es}}</button>
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading">
                    Comidas del dia
                </div>

                <div class="panel-body">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Barbero</th>
                                <th>Sucursal</th>
                                <th>Inicio</th>
                                <th>fin</th>
                                <th>Creado por</th>
                                <th>Creacion</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($eats as $eat)
                                <tr>
                                    <td>{{ $loop->index + 1 }}</td>
                                    <td>{{ $eat->employee->short_name }}</td>
                                    <td>{{ $eat->subsidiary->name }}</td>
                                    <td>{{ $eat->start }}</td>
                                    <td>{{ $eat->end }}</td>
                                    @if($eat->user)
                                        <td>{{ $eat->user->name }}</td>
                                    @elseif($eat->cashier)
                                        <td>{{ $eat->cashier->short_name }}</td>
                                    @else
                                        <td></td>
                                    @endif
                                    <td>{{ $eat->created_at->format('h:i a') }}</td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>

        </div>
    </div>
</div>
@endsection

@section('scripts')
    <script>
        $(document).ready(function () {
            $('#customer_id').on('select2:select', function (){
                $.ajax({
                    type: 'get',
                    dataType: 'json',
                    url: '/home/customers/'+$(this).val(),
                    success: function (res) {
                        $('#phone').val(res.phone)
                    }
                });
            });
        });
    </script>
@endsection

resources/views/admin/diaries/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Citas de hoy
                    <div class="pull-right">
                    @php
                        $user = Auth::user();
                    @endphp
                    @if($user->access_subsidiary_id == null)
                        <a href="{{route('diary.create')}}">Agregar cita</a>
                    @endif
                    </div>
                </div>

                <div class="panel-body">
                    <form action="{{route('diary.index')}}" method="post">
                        {{ csrf_field() }}
                        {{ method_field('GET') }}
                        <div class="form-group">
                            <label for="start">Fecha: </label>
                            <input type="text" class="form-control datepicker" name="start" value="{{$start}}">
                        </div>
                        <div class="form-group">
                            <input type="submit" class="btn btn-default hide-in-print" value="Buscar">
                        </div>
                    </form>
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Código de confirmación</th>
                                <th>Cliente</th>
                                <th>Servicio</th>
                                <th>Teléfono</th>
                                <th>Hora</th>
                                <th>Barbero</th>
                                <th>Fecha de creación</th>
                                <th>Agendado por</th>
                                <th>Atendido</th>
                                @if(!$subdomain)
                                    <th>Sucursal</th>
                                @endif
                                <th>Cancelado</th>
                                @if(Auth::user()->isA('super-admin', 'cashier-admin', 'subsidiary-admin') && $start == \Carbon\Carbon::now()->format('Y-m-d'))
                                    <th>Opciones</th>
                                @endif
                            </tr>
                        </thead>
                        <tbody>

                            @foreach($diaries as $diary)

                                <tr>
                                    <td>{{ $loop->index + 1 }}</td>
                                    <td>{{ $diary->confirmation_code }}</td>
                                    <td>
                                        {{ $diary->created_by_customer ? $diary->customer_name : $diary->customer->name }}
                                        @if($diary->comments)
                                            ({{$diary->comments}}) 
                                        @endif
                                    </td>
                                    <td>
                                        @if($diary->service)
                                            {{$diary->service->name}}
                                        @endif
                                    </td>
                                    <td>{{ $diary->customer->phone }}</td>
                                    <td>{{ $diary->time }}</td>
                                    <td>
                                        {{ $diary->employee ? $diary->employee->short_name : ''}}
                                    </td>
                                    <td>
                                        {{ $diary->created_at->format('h:i a d-m-Y')}}
                                    </td>
                                    @if($diary->user)
                                        <td>{{ $diary->user->name }}</td>
                                    @else
                                        <td>
                                            {{ $diary->cashier ? $diary->cashier->short_name : '' }}
                                            {{ $diary->created_by_customer ? 'Agendado por el cliente' : '' }}
                                        </td>
                                    @endif
                                    <td>{{ $diary->attend ? 'Si' : 'No' }}</td>
                                    @if(!$subdomain)
                                        <td>{{ $diary->subsidiary->name }}</td>
                                    @endif
                                    <td>
                                    @if($diary->canceled)
                                        Si - {{ $diary->updated_at->format('Y-m-d h:i a')}}
                                    @else
                                        No
                                    @endif
                                    </td>
                                    @if(Auth::user()->isA('super-admin', 'cashier-admin', 'subsidiary-admin') && $start >= \Carbon\Carbon::now()->format('Y-m-d'))
                                        <td>
                                            @if(Auth::user()->isA('super-admin', 'cashier-admin', 'subsidiary-admin'))
                                                @if(!$diary->canceled)
                                                    
                                                    <a href="{{route('diary.edit', $diary->id)}}" class="btn btn-info btn-xs">Editar</a>
                                                    <form action="{{route('diary.destroy', $diary->id)}}" method="post">
                                                        {{ csrf_field() }}
                                                        {{ method_field('DELETE') }}
                                                        <input type="submit" class="btn btn-danger btn-xs" value="Cancelar">
                                                    </form>
                                                @endif
                                            @endif
                                        </td>
                                    @endif
                                </tr>
                            @endforeach
                        </tbody>
                    </table>

                </div>

            </div>
        </div>
    </div>
</div>
@endsection